#!/bin/bash
#PBS -N coloc_egfr
#PBS -P cy94
#PBS -q normal
#PBS -l ncpus=4
#PBS -l mem=32GB
#PBS -l walltime=03:00:00
#PBS -l storage=scratch/cy94+gdata/cy94
#PBS -l wd
#PBS -j oe
#PBS -o /scratch/cy94/rs4477/logs/coloc_egfr.log
export MAMBA_EXE=/home/571/rs4477/.local/bin/micromamba
export MAMBA_ROOT_PREFIX=/scratch/cy94/rs4477/micromamba
eval "$($MAMBA_EXE shell hook --shell bash --root-prefix $MAMBA_ROOT_PREFIX)"
micromamba activate mqtl_tensorqtl
cd /scratch/cy94/rs4477/coloc
python /scratch/cy94/rs4477/coloc/fast_coloc_scan.py
