suppressMessages(library(coloc))
args <- commandArgs(trailingOnly=TRUE)
d <- read.table(paste0(args[1],".coloc_input.tsv"), header=TRUE, sep="\t")
cat("variants:", nrow(d), "\n")
D1 <- list(beta=d$mqtl_beta, varbeta=d$mqtl_se^2, snp=as.character(d$snp), MAF=d$mqtl_maf, N=d$mqtl_n[1], type="quant", sdY=1)
D2 <- list(beta=d$gwas_beta, varbeta=d$gwas_se^2, snp=as.character(d$snp), MAF=d$gwas_maf, N=max(d$gwas_n), type="quant", sdY=1)
res <- coloc.abf(D1, D2)
cat("\n=== COLOC:", args[1], "===\n")
print(round(res$summary,4))
cat("\nPP4 (shared causal):", round(res$summary["PP.H4.abf"],3), "\n")
cat("PP3 (distinct causal):", round(res$summary["PP.H3.abf"],3), "\n")
top <- res$results[order(-res$results$SNP.PP.H4),][1:5,c("snp","SNP.PP.H4")]
cat("\nTop shared-causal candidates:\n")
print(top)
